"""Markdown Report Exporter conforming to ReportExporterProtocol and PRD Part 16."""

from core.interfaces import ReportExporterProtocol
from core.issue_model import ReviewResult, SeverityEnum


class MarkdownReportExporter(ReportExporterProtocol):
    """Serializes ReviewResult payload into structured Markdown report."""

    def export(self, result: ReviewResult) -> str:
        """Exports ReviewResult as structured human-readable Markdown string."""
        if not result:
            return "# Code Review Report\n\nNo review data available."

        lines = [
            "# 🛡️ AI Code Review Assistant — Executive Report",
            "",
            "## 1. Executive Summary",
            f"**Overall Score:** `{result.score.overall_score}/100` ({result.score.label})",
            f"**Language:** `{result.language.upper()}`",
            f"**Execution Summary:** {result.summary.executive_summary}",
            "",
            "### Severity Distribution",
            f"- **Critical:** {result.summary.critical_count}",
            f"- **High:** {result.summary.high_count}",
            f"- **Medium:** {result.summary.medium_count}",
            f"- **Low:** {result.summary.low_count}",
            f"- **Informational:** {result.summary.informational_count}",
            "",
            "## 2. Code Quality Breakdown (7 Dimensions)",
            "| Dimension | Score | Weight | Deductions | Issues |",
            "|---|---|---|---|---|",
        ]

        for dim in result.score.dimensions:
            lines.append(
                f"| **{dim.dimension_name}** | `{dim.score}/100` | {int(dim.weight*100)}% | -{dim.deductions} | {dim.issue_count} |"
            )

        lines.extend([
            "",
            "## 3. Findings & Security Audit Results",
        ])

        if not result.issues:
            lines.append("✅ **No code quality or security issues detected.**")
        else:
            for idx, issue in enumerate(result.issues, 1):
                sev_icon = "🔴" if issue.severity in (SeverityEnum.CRITICAL, SeverityEnum.HIGH) else ("🟡" if issue.severity == SeverityEnum.MEDIUM else "🔵")
                lines.extend([
                    f"### Finding #{idx}: {sev_icon} [{issue.severity.value.upper()}] {issue.description}",
                    f"- **Category:** `{issue.category.value}`",
                    f"- **Line:** `{issue.line_start}` to `{issue.line_end}`",
                    f"- **Source:** `{issue.detection_source.value}` ({issue.detecting_tool or 'Static/AI'})",
                    f"- **Code Snippet:** `{issue.code_snippet}`",
                    f"- **Why It Matters:** {issue.why_it_matters}",
                ])

                if issue.fix:
                    lines.extend([
                        "- **Suggested Remediation:**",
                        f"  > {issue.fix.suggested_fix}",
                    ])
                    if issue.fix.diff:
                        lines.extend([
                            "  ```diff",
                            issue.fix.diff.strip(),
                            "  ```",
                        ])

                if issue.generated_test:
                    lines.extend([
                        "- **Generated Test Case:**",
                        "  ```python",
                        issue.generated_test.test_code.strip(),
                        "  ```",
                    ])

                lines.append("")

        lines.extend([
            "---",
            "*Report generated by AI Code Review Assistant Engine*",
        ])

        return "\n".join(lines)
